Add Timeout support
Raqbit/mc-pinger pull request #4
Opened 2021-02-13 12:42 UTC by Herobone

I added an short implementation to support timeouts.
All checks passed (running `_example/main.go` and a custom modification of it to support Timed pings)

Added the new `NewTimed` method to not overwrite the existing method

2021-02-13 12:45 UTC, Herobone commented
Added examples and removed Debug

2021-02-13 14:58 UTC, Raqbit commented
Thank you!

Looks great over all, but I'm wondering if perhaps `context.Context` could be used instead, which would give mc-pinger timeout support for "free" while also adding support for other ways to cancel the ping. 

What do you think?

2021-02-13 15:29 UTC, Herobone commented
changed from `net.DialTimeout` to a use of `context.WithTimeout`. I don't know if that's what you wanted but I think it comes close :-)

2021-02-14 13:27 UTC, Raqbit commented
I was thinking that perhaps a `PingContext` function could accept a context, where the user of the api can pass their own context in which could have a timeout or be tied to some other deadline. This would be in line with how many other apis (Like `Dial` vs `DialContext`) works.

2021-02-14 16:13 UTC, Herobone commented
The `DialContext` Method is not officially exposed, but can be called if you use your own ˋvar d Dialˋ. But I get what you mean.
I will try to implement it later

2021-02-19 09:36 UTC, Herobone commented
Added a new Constructor that accepts a Context. Function with just the Timeout still works
Added a new Example for how to use it with Context

2021-02-20 13:14 UTC, Raqbit requested changes
One small typo, rest looks good to me. 

I do wonder though, with the context version, why there is a need for a separate timeout version if you can simply pass in a context with timeout.

2021-02-20 13:14 UTC, Raqbit commented on chat.go
> +// RegularChatComponent is aMinecraft chat component
```suggestion
// RegularChatComponent is a Minecraft chat component
```

2021-02-21 22:09 UTC, Herobone commented
Fixed

2021-02-21 22:55 UTC, Raqbit approved these changes
LGTM :tada:

2021-02-21 22:57 UTC, merged

2021-02-21 22:58 UTC, Raqbit commented
Thank you for working on this @Herobone :)